name: Java CI

on:
   workflow_dispatch:
   
   
jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    #Checkout the Code
    - name: Step-1 Checkout the code
      uses: actions/checkout@v2
      
    - name: Build maven
      run: 
            mvn clean;
            mvn install;
