# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Step-1 Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command to set up JDK
      - name: Step-2  Setup JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8

      # Runs a set of commands to package the jar
      - name: Step-3 Have GitHub actions Maven Build
        run: mvn -B package --file pom.xml
        
     # Runs a set of commands to check the directory
      - name: Step-4 List the current directory
        run: dir
        
     # Runs a set of commands to check the jar
      - name: Step-5 check target folder
        run: 
          cd target
          dir
        
         
